### ISSUE TITLE
More flexibilty for run inputs - config

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-radiance-workflow#1]
- What if someone wants to use `epw` instead of `wea`?
- How does one configure date-time for studies? Do they need to edit wea file beforehand?

We need to develop a config file or options from command line to support such cases. Here is a quick start.

```yaml
## config.yaml
weather_file: new_location.epw   # this can be a wea or an epw
analysis_period:
  start: 2 Feb
  end: 28 Feb
analysis_hours:
  start: 8
  end: 17
```
